In [1]:
import pandas as pd
import csv

data = pd.read_csv('errors.csv')
print(data.info())
data.sort_values('cosine_dist')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13783 entries, 0 to 13782
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   image_no     13783 non-null  float64
 1   label        13783 non-null  float64
 2   prediction   13783 non-null  float64
 3   cosine_dist  13783 non-null  float64
dtypes: float64(4)
memory usage: 430.8 KB
None

      image_no  label  prediction  cosine_dist
907       47.0   68.0        66.0     0.003464
875       12.0   68.0        66.0     0.003464
876       13.0   68.0        66.0     0.003464
877       14.0   68.0        66.0     0.003464
878       15.0   68.0        66.0     0.003464
...        ...    ...         ...          ...
8741       4.0  660.0       865.0     1.624511
6913      44.0  531.0       584.0     1.627418
9284      46.0  695.0       811.0     1.638438
5451      34.0  445.0       424.0     1.677696
7906      44.0  608.0       603.0     1.751549

[13783 rows x 4 columns]

In [ ]:
grouped = data.groupby('label').agg